# frozen_string_literal: true

source 'https://rubygems.org'

gem 'aws-record', '~> 2.0'
gem 'rating-chgk-v2', '~> 1.5'
gem 'rss', '~> 0.2.9'
gem 'telegram-bot-ruby', '~> 2.0'
gem 'zeitwerk', '~> 2.6'

ruby '~> 3.2.0'
