AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: Bot to track team rating on rating.chgk.info and perform some routine tasks.

Parameters:
  TelegramBotToken:
    Type: String
    Description: Token to use for communication with Telegram severs
    NoEcho: true

Globals:
  Function:
    CodeUri: bot/
    Runtime: ruby2.7

Resources:
  SecretStorage:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: rating_bot_token
      SecretString: !Ref TelegramBotToken

  ChatDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: ChatID
          AttributeType: N
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 10
        WriteCapacityUnits: 10
      TableName: rating_bot_table
      KeySchema:
        - AttributeName: ChatID
          KeyType: HASH

  ProcessCommandFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.message_handler
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Sid: AWSSecretsManagerGetSecretValuePolicy
              Effect: Allow
              Action: secretsmanager:GetSecretValue
              Resource: !Ref SecretStorage
            - Sid: SpecificTable
              Effect: Allow
              Action:
                - "dynamodb:Get*"
                - "dynamodb:BatchGet*"
                - "dynamodb:Scan"
              Resource: 
                Fn::Join:
                  - ''
                  - - "arn:aws:dynamodb:*:*:table/"
                    - !Ref ChatDBTable
