AllCops:
  NewCops: enable

Style/RegexpLiteral:
  EnforcedStyle: percent_r

Style/BlockComments:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Layout/LineLength:
  Enabled: false

Lint/EmptyBlock:
  Enabled: false

# I'm ok with using evan in UT
Security/Eval:
  Enabled: false