# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# The generated `.rspec` file contains `--require spec_helper` which will cause
# this file to always be loaded, without a need to explicitly require it in any
# files.
#
# Given that it is always loaded, you are encouraged to keep this file as
# light-weight as possible. Requiring heavyweight dependencies from this file
# will add to the boot time of your test suite on EVERY test run, even for an
# individual file that may not need all of that loaded. Instead, consider making
# a separate helper file that requires the additional dependencies and performs
# the additional setup, and require it from the spec files that actually need
# it.

require 'timecop'
require 'vcr'
require 'webmock/rspec'
require 'yaml'

$LOAD_PATH.unshift("#{File.dirname(__FILE__ )}/../bot/")

FIXTURES_PATH = File.join File.dirname(__FILE__), 'fixtures'

VCR.configure do |c|
  c.hook_into :faraday
  c.default_cassette_options = {
    decode_compressed_response: true
  }
  c.cassette_library_dir = FIXTURES_PATH
end

RSpec.configure do |config|
  config.expect_with :rspec do |expectations|
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  config.mock_with :rspec do |mocks|
    mocks.verify_partial_doubles = true
  end

  config.shared_context_metadata_behavior = :apply_to_host_groups

  WebMock.allow_net_connect!
  WebMock::API.prepend(Module.new do
    extend self
    def stub_request!(*args)
      VCR.turn_off!
      super
    end
  end)
end
